name: domain
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0-13.0.dev

# Add regular dependencies here.
dependencies:
  intl: any
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_dotenv: ^5.2.1
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
